### ISSUE TITLE
Failed to test and visualize the result using the trained weight

### ISSUE THREAD

**Issue by xbdy** [SJTU-Thinklab-Det/r3det-on-mmdetection#1]
Failed to test on R3Det* mmdetection version based on PyTorch. The screen went blank right after the progress bar appearred. Use `Nvidia-smi`, it returned `Unable to determine the device handle for GPU 0000:01:00.0: GPU is lost.`
Error message:
```
RuntimeError: CUDA error: unspecified launch failure
terminate called after throwing an instance of 'c10::Error'
    what(): CUDA error: unspecified launch failure (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:764)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fabb0a15193 in /home/dfg/anaconda3/envs/torch/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x17f66 (0x7fabb0c52f66 in  /home/dfg/anaconda3/envs/torch/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x19cbd (0x7fabb0c54cbd in  /home/dfg/anaconda3/envs/torch/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #3: c10::TensorImpl::release_resources() + 0x4d (0x7fabb0a0563d in /home/dfg/anaconda3/envs/torch/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x67aba2 (0x7fac0ef38ba2 in  /home/dfg/anaconda3/envs/torch/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x67ac46 (0x7fac0ef38c46 in  /home/dfg/anaconda3/envs/torch/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #22: __libc_start_main + 0xf0 (0x7fac13839830 in /lib/x86_64-linux-gnu/libc.so.6)

RuntimeError: CUDA error: unspecified launch failure
```

**Reproduction**
1. What command or script did you run?
```
sh rtools/test.sh
sh rtools/visualize.sh
```
Both have the same problem.

2. What config dir you run?
```
configs/r3det/r3det_r50_fpn_2x_CustomizeImageSplit.py
```
3. Did you make any modifications on the code or config? Did you understand what you have modified?
I changed the path of the dataset in `configs/r3det/datasets/dotav1_rotational_detection.py`
4. What dataset did you use?
DOTA1.0

**Environment**

TorchVision: 0.5.0
OpenCV: 4.2.0
MMCV: 0.5.9
MMDetection: 2.1.0+unknown
MMDetection Compiler: GCC 5.4
MMDetection CUDA Compiler: 10.1

**Comment by zhanggefan** [comment]
Hi xbdy
It looks like a CUDA related failure. Can you provide more details? 
1. What type of GPU did you use? 
2. did you run 'python setup.py install' to build the cuda extensions and install the package before your experiment? Did it run successfully?

**Comment by xbdy** [comment]
Thank you for your reply.
1. The GPU I use is RTX 2080Ti, only one GPU.
2. I did run `python setup.py install`, but in a virtual environment where I have installed pytorch 1.4.0 before. And there was no errors or warnings while running `setup.py`.

I have also tried the tensorflow version of R3Det. I tested my own pictures on the R3Det++ trained weight with backbone ResNet50_v1d 600->800 successfully, but failed on that with backbone ResNet152_v1d MS. The trained weights come from [https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/MODEL_ZOO.md](url). The error messages are similar to those of the mmdetection version, and GPU is also lost.

Is it possible that different CUDA version caused this? Though I haven't tried other CUDA versions.

**Comment by zhanggefan** [comment]
I am sorry for it but CUDA-related failures are really hard to reproduce...
I also use a single 2080Ti but got no error when experimenting with both MMDet / TensorFlow versions of R3Det. And I find nothing in particular with your software environment. (Though I do not have enough resources to test it).
It may have something to do with your hardware & GPU driver since hardware or driver failure is a major cause of 'GPU lost'.
Have you tried training/testing an original MMDetection model? It is an easy approach to check whether the problem is related to the code or specific to your machine.

**Comment by xbdy** [comment]
It seems to be the hardware problem. I try the TensorFlow version on another work station with 2 TITAN XP and all goes well. 
Anyway, thank you very much!
