### ISSUE TITLE
log "completed: 0, elapsed: 0s" while running rtools/test.sh

### ISSUE THREAD

**Issue by sunbuhui** [SJTU-Thinklab-Det/r3det-on-mmdetection#16]
My env:
colab:
pytorch1.7.0
cuda10.1
mmdection 2.1.0
mmcv 0.5.9
My problem:
I want to test if I can run the model, so I download the trained model from this repo given link https://drive.google.com/file/d/1JYyEHyzloRcxYlSRuiCLEaCjjj4Q7L_E/view?usp=sharing
And I am sure that I have put in the right position.
I doesn't use the .sh command
`sh rtools/test.sh
`
but I choose 
`!PYTHONPATH=${PWD}:$PYTHONPATH python tools/test.py configs/r3det/r3det_r50_fpn_2x_CustomizeImageSplit.py work_dirs/r3det_r50_fpn_2x_20200616/epoch_24.pth --format-only --options submission_dir=work_dirs/r3det_r50_fpn_2x_20200616/submission`
I add "!PYTHONPATH=${PWD}:$PYTHONPATH",only in this way can I run the test program.
related issue link  https://github.com/open-mmlab/mmdetection/issues/2667
 so when I start testing, it shows the log below
`completed: 0, elapsed: 0s
`
And I open the task1-xxx.txt, it shows nothing.
Should I download the DOTA dataset and should I put it in the postion mentioned in  dota_image_split.py?
In general, I want to know if it's the right output, if I am wrong, can you please tell me how to solve it?
I an unfamiliar with computer vision, sorry for raising this question.
I will try to train model by myself later, thanks!

**Comment by sunbuhui** [comment]
@zhanggefan can you please take a look at it?

**Comment by sunbuhui** [comment]
oh, I think I needn't solve this problem now since I wrote a test code myself, I will note my fault later in this issue.

**Comment by tjmannn** [comment]
hello, could you explain how to solve this problem @sunbuhui

**Comment by tjmannn** [comment]
I misset the testset path, sorry for disturbance

**Comment by xhowdonewd** [comment]
ha? sorry, I met the same Q. How can you solve this?

**Comment by sunbuhui** [comment]
@niudaohong It's been a long time, I have forgot it, sorry. You can copy the script it calls and run it yourself

**Comment by sunbuhui** [comment]
@niudaohong I remember that the test.sh calls a python script, you can check the python script and copy this code and run it in your IDEs.

**Comment by xhowdonewd** [comment]
> @niudaohong I remember that the test.sh calls a python script, you can check the python script and copy this code and run it in your IDEs.

yeah, I have tried both .py and sh. The same question happened. I don't know how to solve this. I want to use demo files to test the results.

**Comment by sunbuhui** [comment]
@niudaohong maybe dataset path? I mixed up the path before, and @tjmannn also reminded that cause.

**Comment by xhowdonewd** [comment]
> @niudaohong maybe dataset path? I mixed up the path before, and @tjmannn also reminded that cause.

Thank you ! I think you're right the path is wrong,  but I can't fix it
