### ISSUE TITLE
ImportError: dynamic module does not define module export function(PyInit_geo_cuda)

### ISSUE THREAD

**Issue by trulyjupiter** [SJTU-Thinklab-Det/r3det-on-mmdetection#2]
Failed to train on R3Det* mmdetection version based on PyTorch. I got an import error when running sh rtools/train.sh

Error message:
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/apis/inference.py", line 9, in <module>
    from mmdet.core import get_classes
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/bbox/__init__.py", line 1, in <module>
    from .assigners import (AssignResult, BaseAssigner, CenterRegionAssigner,
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/bbox/assigners/__init__.py", line 1, in <module>
    from .approx_max_iou_assigner import ApproxMaxIoUAssigner
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/bbox/assigners/approx_max_iou_assigner.py", line 4, in <module>
    from ..iou_calculators import build_iou_calculator
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/bbox/iou_calculators/__init__.py", line 3, in <module>
    from .riou2d_calculator import RBboxOverlaps2D, rbbox_overlaps
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/bbox/iou_calculators/riou2d_calculator.py", line 1, in <module>
    from mmdet.ops import rbbox_iou_iof
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/ops/__init__.py", line 19, in <module>
    from .rbbox_geo import rbbox_iou_iof
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/ops/rbbox_geo/__init__.py", line 1, in <module>
    from .rbbox_geo import rbbox_iou_iof
  File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/ops/rbbox_geo/rbbox_geo.py", line 1, in <module>
    from . import rbbox_geo_cuda
ImportError: dynamic module does not define module export function (PyInit_rbbox_geo_cuda)

But no errors reported during compilation and my environment is:
torch:1.5.0
torchvision: 0.6.0
mmdet: 2.1.0+8f3868f
GCC: 7.3
CUDA : 10.1
CUDNN:7.5.1
The GPU is RTX 2080, only one GPU.

**Comment by zhanggefan** [comment]
Hi, trulyjupiter,
The error messages show that the library file `rbbox_geo_cuda.cpython-***.so` is not correctly built. It fails to export a global function `PyInit_rbbox_geo_cuda`. 
This .so file is located under the directory `{your local repo}/mmdet/ops/rbbox_geo`. You can check the exported symbol table by `cd` into the directory and run bash command `nm -D *.so | grep PyInit`. If nothing shows up, then it means that you will need at least to recompile the library. 
> Besides, only as a reminder, the RTX 2080 has 8GB GRAM and is insufficient to train r50-r3det* with a batch size of 6 (default value), which would take up to 10GB. You can change the batch size at line 46 of file `{your local repo}/configs/r3det/datasets/dotav1_rotational_detection.py`.

**Comment by trulyjupiter** [comment]
Thanks for your reply. I have run the command “ nm -D *.so | grep PyInit” but find nothing. Then I recompile the whole library by running command “python setup.py install”. But the problem still exists. I wonder if it is a problem caused by torch version. Can you tell me your environment?
Besides, thanks for your reminder. I will change the batch size as you suggested.

**Comment by zhanggefan** [comment]
My environment:
* Ubuntu 18.04.3
* Python 3.8
* PyTorch 1.5
* TorchVision 0.6.0
* CUDA 10.2.89
* CUDNN 7.6.4
* Nvidia-Driver 440.33.01
* GCC 7.5.0

You may also use the docker-image `zhanggefan/rmmdet`. I have tested the image with docker version 19.03.11, and with the following command:
`sudo docker run --gpus all -it --shm-size 16g -v {your dataset location}:/data/dota zhanggefan/rmmdet bash`

**Comment by trulyjupiter** [comment]
Thanks for your reply! I have solved this problem by reinstalling the environment.

**Comment by Pengfei-Chen20** [comment]
> Failed to train on R3Det* mmdetection version based on PyTorch. I got an import error when running sh rtools/train.sh
> 
> Error message:
> Traceback (most recent call last):
> File "tools/train.py", line 13, in
> from mmdet.apis import set_random_seed, train_detector
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/apis/**init**.py", line 1, in
> from .inference import (async_inference_detector, inference_detector,
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/apis/inference.py", line 9, in
> from mmdet.core import get_classes
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/**init**.py", line 2, in
> from .bbox import * # noqa: F401, F403
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/bbox/**init**.py", line 1, in
> from .assigners import (AssignResult, BaseAssigner, CenterRegionAssigner,
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/bbox/assigners/**init**.py", line 1, in
> from .approx_max_iou_assigner import ApproxMaxIoUAssigner
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/bbox/assigners/approx_max_iou_assigner.py", line 4, in
> from ..iou_calculators import build_iou_calculator
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/bbox/iou_calculators/**init**.py", line 3, in
> from .riou2d_calculator import RBboxOverlaps2D, rbbox_overlaps
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/core/bbox/iou_calculators/riou2d_calculator.py", line 1, in
> from mmdet.ops import rbbox_iou_iof
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/ops/**init**.py", line 19, in
> from .rbbox_geo import rbbox_iou_iof
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/ops/rbbox_geo/**init**.py", line 1, in
> from .rbbox_geo import rbbox_iou_iof
> File "/home/ubuntu/anaconda3/envs/pytorch1.5/lib/python3.6/site-packages/mmdet-2.1.0+8f3868f-py3.6-linux-x86_64.egg/mmdet/ops/rbbox_geo/rbbox_geo.py", line 1, in
> from . import rbbox_geo_cuda
> ImportError: dynamic module does not define module export function (PyInit_rbbox_geo_cuda)
> 
> But no errors reported during compilation and my environment is:
> torch:1.5.0
> torchvision: 0.6.0
> mmdet: 2.1.0+8f3868f
> GCC: 7.3
> CUDA : 10.1
> CUDNN:7.5.1
> The GPU is RTX 2080, only one GPU.

H

> Thanks for your reply! I have solved this problem by reinstalling the environment.

Hi,bro
U sad u have solved the problem by reinstalling your environment. I have the same problem, so I wanna how did u solve this problem. 
My environment is:
pytorch 1.5.0
torchvision 0.6.0
cuda 10.1
cudnn 7.6.3
Thank U !

**Comment by trulyjupiter** [comment]
I re-created a virtual environment and followed the installation process step by step.

**Comment by HsLOL** [comment]
@trulyjupiter  
Could you please make a list of the installation process.
I want to know a right order of install process.
thank you very much!

**Comment by HsLOL** [comment]
@zhanggefan 
hi 
I have the same problem as @trulyjupiter 
But he said he reinstall the environment to solve the problem. Then I reinstall my environment,when I run the " python setup.py install "  it has a import error" ValueError: Unknown CUDA arch (8.6) or GPU not supported".How can I solve this problem.

My environment
Python 3.8.5
Pytorch 1.5.0
Torchvision 0.6.0
CUDA 10.1.243
CUDNN 7.6.4


when I update the cudatoolkit, I run the "conda install cudatoolkit==10.2.89" it has the  problem.

UnsatisfiableError: The following specifications were found to be in conflict:
  - cudatoolkit==10.2.89
  - python=3.8
  - pytorch==1.5.0
Use "conda info <package>" to see the dependencies for each package.
