### ISSUE TITLE
Problems with sh rtools/train.sh && sh rtools/test.sh: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l

### ISSUE THREAD

**Issue by TonyLi-Shu** [SJTU-Thinklab-Det/r3det-on-mmdetection#30]
I encounter a problem while getting start with repos. I followed the step and I finish data split and py setup.py.
However, I had a same problem with both test.sh and train.sh:

ImportError: /home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/ops/corner_pool/corner_pool_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l

I currently running this command on a linux server with conda environment as requirement.txt
I wonder if this problem occur due to this file-->corner_pool_ext.cpython-36m-x86_64-linux-gnu.so
Thanks everyone who are going to help me in advance! I dont know if anyone encounter the same question.

Here is my Detail Problems:
(r3det-pytorch) shenzy@AI:~/lsd_temp_file/r3det-on-mmdetection$ sh rtools/train.sh
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/apis/inference.py", line 9, in <module>
    from mmdet.core import get_classes
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/core/bbox/__init__.py", line 1, in <module>
    from .assigners import (AssignResult, BaseAssigner, CenterRegionAssigner,
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/core/bbox/assigners/__init__.py", line 1, in <module>
    from .approx_max_iou_assigner import ApproxMaxIoUAssigner
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/core/bbox/assigners/approx_max_iou_assigner.py", line 4, in <module>
    from ..iou_calculators import build_iou_calculator
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/core/bbox/iou_calculators/__init__.py", line 3, in <module>
    from .riou2d_calculator import RBboxOverlaps2D, rbbox_overlaps
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/core/bbox/iou_calculators/riou2d_calculator.py", line 1, in <module>
    from mmdet.ops import rbbox_iou_iof
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/ops/__init__.py", line 3, in <module>
    from .corner_pool import CornerPool
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/ops/corner_pool/__init__.py", line 1, in <module>
    from .corner_pool import CornerPool
  File "/home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/ops/corner_pool/corner_pool.py", line 4, in <module>
    from . import corner_pool_ext
ImportError: /home/shenzy/lsd_temp_file/r3det-on-mmdetection/mmdet/ops/corner_pool/corner_pool_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l

**Comment by TonyLi-Shu** [comment]
### I SOLVE IT BY **Reinstall everything (environments + github code)**
Here is the view of training model


As far as I am concerned, this problem occurs because some packages were not fully install during the command:
`python setup.py install`
And the reason this command can not fully run is because you need to install a few packages before running this command
Here is the detail steps: **(I run my code on Linux server, or it may be only useful to the people who use linux)**

1. First, you need to setup your conda environment `conda create -n  (your env name) python=3.6`

2. Then you need to get in the env by running this command `conda activate (your env name)`

3. Second, and **here comes the most important part.** You need to install some packages before running the setup.py:
1)  you need to install pytorch from https://pytorch.org/get-started/previous-versions/ 
mine version is `conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch`
But Plz **check your cuda version**, you need to install pytorch that following the cuda version
And **I personally recommand you to use mirror** if you are in China. More Detail about How to download pytorch from mirror.
You can check online from Google or Baidu. Since installing pytorch and torchvision always failed when you install directly.

2) Plus you also need install mmcv==0.6.1 & pycocotools.
You can install these by running the command:
`pip install pycocotools`
`conda/pip install  mmcv==0.6.1`

3. Then you can get into the folder of this project by `cd ~/r3det-on-mmdetection` 
4. And run the command `python setup.py install` **What's more you need to make sure your internet is fine since during the command you probably need to download some weight or file from internet.**

**it is my first time raise a question and answer by myself
I hope my suggestion would work for you**

Here is the view of successful running of train.sh

_(r3detpytorch) lsd@hello:~/lsd_temp_file/r3det-on-mmdetection$ sh rtools/train.sh
/home/lsd/anaconda3/envs/r3detpytorch/lib/python3.7/site-packages/mmcv/utils/registry.py:64: UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  'The old API of register_module(module, force=False) '
2021-07-16 16:25:40,111 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
CUDA available: True
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29069683_0
GPU 0,1: TITAN Xp
GCC: gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
PyTorch: 1.8.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.3-Product Build 20210617 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.9.0
OpenCV: 4.5.3
MMCV: 0.6.1
MMDetection: 2.1.0+8f3868f
MMDetection Compiler: GCC 9.3
MMDetection CUDA Compiler: 11.1
------------------------------------------------------------

2021-07-16 16:25:40,111 - mmdet - INFO - Distributed training: False
2021-07-16 16:25:40,776 - mmdet - INFO - Config:
model = dict(
    type='R3Det',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_input',
        num_outs=5),
    bbox_head=dict(
        type='RRetinaHead',
        num_classes=15,
        in_channels=256,
        stacked_convs=4,
        use_h_gt=True,
        feat_channels=256,
        anchor_generator=dict(
            type='RAnchorGenerator',
            octave_base_scale=4,
            scales_per_octave=3,
            ratios=[1.0, 0.5, 2.0, 0.3333333333333333, 3.0, 0.2, 5.0],
            angles=None,
            strides=[8, 16, 32, 64, 128]),
        bbox_coder=dict(
            type='DeltaXYWHABBoxCoder',
            target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
            target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='SmoothL1Loss', beta=0.11, loss_weight=1.0)),
    frm_cfgs=[
        dict(in_channels=256, featmap_strides=[8, 16, 32, 64, 128]),
        dict(in_channels=256, featmap_strides=[8, 16, 32, 64, 128])
    ],
    num_refine_stages=2,
    refine_heads=[
        dict(
            type='RRetinaRefineHead',
            num_classes=15,
            in_channels=256,
            stacked_convs=4,
            feat_channels=256,
            anchor_generator=dict(
                type='PseudoAnchorGenerator', strides=[8, 16, 32, 64, 128]),
            bbox_coder=dict(
                type='DeltaXYWHABBoxCoder',
                target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
                target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
            loss_cls=dict(
                type='FocalLoss',
                use_sigmoid=True,
                gamma=2.0,
                alpha=0.25,
                loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=0.11, loss_weight=1.0)),
        dict(
            type='RRetinaRefineHead',
            num_classes=15,
            in_channels=256,
            stacked_convs=4,
            feat_channels=256,
            anchor_generator=dict(
                type='PseudoAnchorGenerator', strides=[8, 16, 32, 64, 128]),
            bbox_coder=dict(
                type='DeltaXYWHABBoxCoder',
                target_means=(0.0, 0.0, 0.0, 0.0, 0.0),
                target_stds=(1.0, 1.0, 1.0, 1.0, 1.0)),
            loss_cls=dict(
                type='FocalLoss',
                use_sigmoid=True,
                gamma=2.0,
                alpha=0.25,
                loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=0.11, loss_weight=1.0))
    ])
train_cfg = dict(
    s0=dict(
        assigner=dict(
            type='MaxIoUAssigner',
            pos_iou_thr=0.5,
            neg_iou_thr=0.4,
            min_pos_iou=0,
            ignore_iof_thr=-1,
            iou_calculator=dict(type='RBboxOverlaps2D')),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    sr=[
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.6,
                neg_iou_thr=0.5,
                min_pos_iou=0,
                ignore_iof_thr=-1,
                iou_calculator=dict(type='RBboxOverlaps2D')),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.6,
                min_pos_iou=0,
                ignore_iof_thr=-1,
                iou_calculator=dict(type='RBboxOverlaps2D')),
            allowed_border=-1,
            pos_weight=-1,
            debug=False)
    ],
    stage_loss_weights=[1.0, 1.0])
merge_nms_iou_thr_dict = dict({
    'roundabout': 0.1,
    'tennis-court': 0.3,
    'swimming-pool': 0.1,
    'storage-tank': 0.1,
    'soccer-ball-field': 0.3,
    'small-vehicle': 0.05,
    'ship': 0.05,
    'plane': 0.3,
    'large-vehicle': 0.05,
    'helicopter': 0.2,
    'harbor': 0.0001,
    'ground-track-field': 0.3,
    'bridge': 0.0001,
    'basketball-court': 0.3,
    'baseball-diamond': 0.3
})
merge_cfg = dict(
    nms_pre=2000,
    score_thr=0.1,
    nms=dict(
        type='rnms',
        iou_thr=dict({
            'roundabout': 0.1,
            'tennis-court': 0.3,
            'swimming-pool': 0.1,
            'storage-tank': 0.1,
            'soccer-ball-field': 0.3,
            'small-vehicle': 0.05,
            'ship': 0.05,
            'plane': 0.3,
            'large-vehicle': 0.05,
            'helicopter': 0.2,
            'harbor': 0.0001,
            'ground-track-field': 0.3,
            'bridge': 0.0001,
            'basketball-court': 0.3,
            'baseball-diamond': 0.3
        })),
    max_per_img=1000)
test_cfg = dict(
    nms_pre=1000,
    score_thr=0.1,
    nms=dict(type='rnms', iou_thr=0.05),
    max_per_img=100,
    merge_cfg=dict(
        nms_pre=2000,
        score_thr=0.1,
        nms=dict(
            type='rnms',
            iou_thr=dict({
                'roundabout': 0.1,
                'tennis-court': 0.3,
                'swimming-pool': 0.1,
                'storage-tank': 0.1,
                'soccer-ball-field': 0.3,
                'small-vehicle': 0.05,
                'ship': 0.05,
                'plane': 0.3,
                'large-vehicle': 0.05,
                'helicopter': 0.2,
                'harbor': 0.0001,
                'ground-track-field': 0.3,
                'bridge': 0.0001,
                'basketball-court': 0.3,
                'baseball-diamond': 0.3
            })),
        max_per_img=1000))
dataset_type = 'DOTADatasetV1'
data_root = '/mnt/new_disk/shenzy/DOTA10/DOTA/'
trainsplit_ann_folder = 'trainsplit/labelTxt'
trainsplit_img_folder = 'trainsplit/images'
valsplit_ann_folder = 'valsplit/labelTxt'
valsplit_img_folder = 'valsplit/images'
val_ann_folder = 'val/labelTxt'
val_img_folder = 'val/images'
test_img_folder = 'test/images'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize', img_scale=(800, 800)),
    dict(type='RRandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size=(800, 800)),
    dict(type='DefaultFormatBundle'),
    dict(
        type='Collect',
        keys=['img', 'gt_bboxes', 'gt_labels', 'gt_bboxes_ignore'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='CroppedTilesFlipAug',
        tile_scale=(800, 800),
        tile_shape=(600, 600),
        tile_overlap=(150, 150),
        flip=False,
        transforms=[
            dict(type='RResize', img_scale=(800, 800)),
            dict(type='RRandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size=(800, 800)),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=6,
    workers_per_gpu=2,
    train=[
        dict(
            type='DOTADatasetV1',
            data_root='/mnt/new_disk/shenzy/DOTA10/DOTA/',
            ann_file='trainsplit/labelTxt',
            img_prefix='trainsplit/images',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(type='RResize', img_scale=(800, 800)),
                dict(type='RRandomFlip', flip_ratio=0.5),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[58.395, 57.12, 57.375],
                    to_rgb=True),
                dict(type='Pad', size=(800, 800)),
                dict(type='DefaultFormatBundle'),
                dict(
                    type='Collect',
                    keys=['img', 'gt_bboxes', 'gt_labels', 'gt_bboxes_ignore'])
            ]),
        dict(
            type='DOTADatasetV1',
            data_root='/mnt/new_disk/shenzy/DOTA10/DOTA/',
            ann_file='valsplit/labelTxt',
            img_prefix='valsplit/images',
            pipeline=[
                dict(type='LoadImageFromFile'),
                dict(type='LoadAnnotations', with_bbox=True),
                dict(type='RResize', img_scale=(800, 800)),
                dict(type='RRandomFlip', flip_ratio=0.5),
                dict(
                    type='Normalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[58.395, 57.12, 57.375],
                    to_rgb=True),
                dict(type='Pad', size=(800, 800)),
                dict(type='DefaultFormatBundle'),
                dict(
                    type='Collect',
                    keys=['img', 'gt_bboxes', 'gt_labels', 'gt_bboxes_ignore'])
            ])
    ],
    val=dict(
        type='DOTADatasetV1',
        data_root='/mnt/new_disk/shenzy/DOTA10/DOTA/',
        ann_file='val/labelTxt',
        difficulty_thresh=1,
        img_prefix='val/images',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='CroppedTilesFlipAug',
                tile_scale=(800, 800),
                tile_shape=(600, 600),
                tile_overlap=(150, 150),
                flip=False,
                transforms=[
                    dict(type='RResize', img_scale=(800, 800)),
                    dict(type='RRandomFlip', flip_ratio=0.5),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size=(800, 800)),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='DOTADatasetV1',
        data_root='/mnt/new_disk/shenzy/DOTA10/DOTA/',
        ann_file='test/images',
        difficulty_thresh=1,
        img_prefix='test/images',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='CroppedTilesFlipAug',
                tile_scale=(800, 800),
                tile_shape=(600, 600),
                tile_overlap=(150, 150),
                flip=False,
                transforms=[
                    dict(type='RResize', img_scale=(800, 800)),
                    dict(type='RRandomFlip', flip_ratio=0.5),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size=(800, 800)),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
optimizer = dict(type='SGD', lr=0.004, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=10, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=5000,
    warmup_ratio=0.1,
    step=[12, 16, 20])
total_epochs = 24
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
work_dir = './work_dirs/r3det_r50_fpn_2x_20200616'
evaluation = dict(interval=1, metric='mAP')
gpu_ids = range(0, 1)

2021-07-16 16:25:41,531 - mmdet - INFO - load model from: torchvision://resnet50
2021-07-16 16:25:41,964 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

/home/lsd/anaconda3/envs/r3detpytorch/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py:168: UserWarning: Runner was deprecated, please use EpochBasedRunner instead
  'Runner was deprecated, please use EpochBasedRunner instead')
/home/lsd/anaconda3/envs/r3detpytorch/lib/python3.7/site-packages/mmcv/runner/base_runner.py:59: UserWarning: batch_processor is deprecated, please implement train_step() and val_step() in the model instead.
  warnings.warn('batch_processor is deprecated, please implement '
2021-07-16 16:25:49,240 - mmdet - INFO - Start running, host: shenzy@AI, work_dir: /home/shenzy/lsd_temp_file/r3det-on-mmdetection/work_dirs/r3det_r50_fpn_2x_20200616
2021-07-16 16:25:49,240 - mmdet - INFO - workflow: [('train', 1)], max: 24 epochs
/home/lsd/anaconda3/envs/r3detpytorch/lib/python3.7/site-packages/mmdet-2.1.0+8f3868f-py3.7-linux-x86_64.egg/mmdet/core/bbox/coder/delta_xywha_bbox_coder.py:101: UserWarning: This overload of addcmul is deprecated:
        addcmul(Tensor input, Number value, Tensor tensor1, Tensor tensor2, *, Tensor out)
Consider using one of the following signatures instead:
        addcmul(Tensor input, Tensor tensor1, Tensor tensor2, *, Number value, Tensor out) (Triggered internally at  /opt/conda/conda-bld/pytorch_1614378124864/work/torch/csrc/utils/python_arg_parser.cpp:1005.)
  gx = torch.addcmul(px, 1, pw, dx)  # gx = px + pw * dx
2021-07-16 16:26:47,673 - mmdet - INFO - Epoch [1][50/1929]     lr: 4.353e-04, eta: 15:00:42, time: 1.169, data_time: 0.060, memory: 6927, s0.loss_cls: 1.1418, s0.loss_bbox: 1.8719, sr0.loss_cls: 1.1464, sr0.loss_bbox: 1.9118, sr1.loss_cls: 1.1468, sr1.loss_bbox: 1.7721, loss: 8.9907, grad_norm: 5.5405_

**Comment by wb014** [comment]
reference:https://github.com/open-mmlab/mmdetection/issues/3005

> python3 setup.py develop without delete the mmdet dir in Pycharm.
python3 setup.py install with delete the mmdet dir in Pycharm.

I just ran "python3 setup.py develop without delete the mmdet dir in Pycharm." and it worked
