### ISSUE TITLE
KeyError: 'ConvWS is already registered in conv layer'

### ISSUE THREAD

**Issue by Richard-mei** [SJTU-Thinklab-Det/r3det-on-mmdetection#5]
When i run train.py, this error occured.

  File "/home/***/PycharmProjects/Oriented_object_detect/r3det-on-mmdetection/mmdet/ops/conv_ws.py", line 23, in <module>
    class ConvWS2d(nn.Conv2d):
  File "/home/***/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 122, in _register
    module_class=cls, module_name=name, force=force)
  File "/home/***/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 58, in _register_module
    raise KeyError(f'{module_name} is already registered '
KeyError: 'ConvWS is already registered in conv layer'

**Comment by nimaone** [comment]
> When i run train.py, this error occured.
> 
> File "/home/_**/PycharmProjects/Oriented_object_detect/r3det-on-mmdetection/mmdet/ops/conv_ws.py", line 23, in class ConvWS2d(nn.Conv2d): File "/home/**_/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 122, in _register
> module_class=cls, module_name=name, force=force)
> File "/home/***/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 58, in _register_module
> raise KeyError(f'{module_name} is already registered '
> KeyError: 'ConvWS is already registered in conv layer'

use this structure and everything will be OK 





# install dependencies: (use cu101 because colab has CUDA 10.1)
!pip install -U torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html

# install mmcv  that match mmdetection version 2.1.0
!pip install mmcv==0.6.1

# Install mmdetection
!rm -rf r3det-on-mmdetection
!git clone https://github.com/SJTU-Thinklab-Det/r3det-on-mmdetection
%cd r3det-on-mmdetection
!pip install -r requirements/build.txt
!pip install -v -e .  # or "python setup.py develop"

 install Pillow 7.0.0 back in order to avoid bug in colab
!pip install Pillow==7.0.0

**Comment by Richard-mei** [comment]
It does work for me. Thank you!

**Comment by HsLOL** [comment]
> > When i run train.py, this error occured.
> > File "/home/_**/PycharmProjects/Oriented_object_detect/r3det-on-mmdetection/mmdet/ops/conv_ws.py", line 23, in class ConvWS2d(nn.Conv2d): File "/home/**_/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 122, in _register
> > module_class=cls, module_name=name, force=force)
> > File "/home/***/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 58, in _register_module
> > raise KeyError(f'{module_name} is already registered '
> > KeyError: 'ConvWS is already registered in conv layer'
> 
> use this structure and everything will be OK
> 
> # install dependencies: (use cu101 because colab has CUDA 10.1)
> !pip install -U torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
> 
> # install mmcv that match mmdetection version 2.1.0
> !pip install mmcv==0.6.1
> 
> # Install mmdetection
> !rm -rf r3det-on-mmdetection
> !git clone https://github.com/SJTU-Thinklab-Det/r3det-on-mmdetection
> %cd r3det-on-mmdetection
> !pip install -r requirements/build.txt
> !pip install -v -e . # or "python setup.py develop"
> 
> install Pillow 7.0.0 back in order to avoid bug in colab
> !pip install Pillow==7.0.0

hi @nimaone 
I follow your steps. But, when i run the **!pip install -v -e . # or "python setup.py develop"**, there is an error like this.

> ERROR: Command errored out with exit status 1: /home/user/anaconda3/envs/R3Det/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/user/code/r3det-on-mmdetection/setup.py'"'"'; __file__='"'"'/home/user/code/r3det-on-mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

How can I solve this problem?
Thanks a lot

**Comment by Richard-mei** [comment]
https://stackoverflow.com/questions/63508264/how-i-can-solve-the-error-command-errored-out-with-exit-status-1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SJTU-Thinklab-Det/r3det-on-mmdetection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月23日(星期五) 下午4:12
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [SJTU-Thinklab-Det/r3det-on-mmdetection] KeyError: 'ConvWS is already registered in conv layer' (#5)





   
When i run train.py, this error occured.
 File "/home//PycharmProjects/Oriented_object_detect/r3det-on-mmdetection/mmdet/ops/conv_ws.py", line 23, in class ConvWS2d(nn.Conv2d): File "/home//anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 122, in _register
 module_class=cls, module_name=name, force=force)
 File "/home/***/anaconda3/envs/mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 58, in _register_module
 raise KeyError(f'{module_name} is already registered '
 KeyError: 'ConvWS is already registered in conv layer'
  
use this structure and everything will be OK
 
install dependencies: (use cu101 because colab has CUDA 10.1)
 
!pip install -U torch==1.5.1+cu101 torchvision==0.6.1+cu101 -f https://download.pytorch.org/whl/torch_stable.html
 
install mmcv that match mmdetection version 2.1.0
 
!pip install mmcv==0.6.1
 
Install mmdetection
 
!rm -rf r3det-on-mmdetection
 !git clone https://github.com/SJTU-Thinklab-Det/r3det-on-mmdetection
 %cd r3det-on-mmdetection
 !pip install -r requirements/build.txt
 !pip install -v -e . # or "python setup.py develop"
 
install Pillow 7.0.0 back in order to avoid bug in colab
 !pip install Pillow==7.0.0
  
hi @nimaone
 I follow your steps. But, when i run the !pip install -v -e . # or "python setup.py develop", there is an error like this.
  
ERROR: Command errored out with exit status 1: /home/user/anaconda3/envs/R3Det/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/user/code/r3det-on-mmdetection/setup.py'"'"'; file='"'"'/home/user/code/r3det-on-mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
  
How can I solve this problem?
 Thanks a lot
